// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.example.grpc.messaging;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
