// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.example.grpc.messaging;

public interface MessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.MessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  java.util.List<Message>
      getMessagesList();
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  Message getMessages(int index);
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  java.util.List<? extends MessageOrBuilder>
      getMessagesOrBuilderList();
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  MessageOrBuilder getMessagesOrBuilder(
      int index);
}
