// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package messaging;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender_id = 1;</code>
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiver_id = 2;</code>
   */
  java.lang.String getReceiverId();
  /**
   * <code>string receiver_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
