// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package messaging;

public interface MessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.MessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  java.util.List<messaging.Message> 
      getMessagesList();
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  messaging.Message getMessages(int index);
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  java.util.List<? extends messaging.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .messaging.Message messages = 1;</code>
   */
  messaging.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
